POST http://127.0.0.1:8080/shoping/instock
Content-Type: application/json


{
  "Goods_list":	[
    {
      "Goods_id":17,
      "Original_price":6.6,
      "Amount":51
    }
  ,
    {
      "Goods_id":19,
      "Original_price":42.0,
      "Amount":23
    },
    {
      "Goods_id":6,
      "Original_price":50.0,
      "Amount":45
    }
  ],
  "Supplier_id":9
}


###