POST http://127.0.0.1:8080/shoping/instock
Content-Type: application/json


{
  "Goods_list":	[
    {
      "Goods_id":21,
      "Original_price":52.0,
      "Amount":21.00
    }
  ,
    {
      "Goods_id":23,
      "Original_price":22.0,
      "Amount":23.00
    }
  ],
  "Supplier_id":9
}


###