POST http://127.0.0.1:8080/shoping/instock
Content-Type: application/json


{
  "Goods_list":	[
    {
      "Goods_id":21,
      "Original_price":6.6,
      "Amount":51
    }
  ,
    {
      "Goods_id":23,
      "Original_price":42.0,
      "Amount":23
    }
  ],
  "Supplier_id":7
}


###