POST http://127.0.0.1:8080/outgoods/outgood
Content-Type: application/json


{
  "orderNumber":"20200410S0009",
  "userId": 1,
  "outlist":[
    {
      "goodId":6,
      "amount":1.0
    }

  ]
}




###